### ISSUE TITLE
 'Trade' object has no attribute 'open_date_utc'

### ISSUE THREAD

**Issue by ladismrkolj** [werkkrew/freqtrade-strategies#1]
I get this error, running the default hyperopt, no files changed, except for the stake currency. I am running latest docker technical image on docker desktop on Win10.

`Unexpected error 'Trade' object has no attribute 'open_date_utc' calling <bound method Solipsis3.custom_stoploss of <Solipsis_USDT.Solipsis_USDT object at 0x7f45c7b99130>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/user_data/strategies/Solipsis_v3.py", line 353, in custom_stoploss
    trade_dur = int((current_time.timestamp() - trade.open_date_utc.timestamp()) // 60)
AttributeError: 'Trade' object has no attribute 'open_date_utc'
Unexpected error 'Trade' object has no attribute 'open_date_utc' calling <bound method Solipsis3.custom_stoploss of <Solipsis_USDT.Solipsis_USDT object at 0x7f10a882a130>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/user_data/strategies/Solipsis_v3.py", line 353, in custom_stoploss
    trade_dur = int((current_time.timestamp() - trade.open_date_utc.timestamp()) // 60)
AttributeError: 'Trade' object has no attribute 'open_date_utc'
Unexpected error 'Trade' object has no attribute 'open_date_utc' calling <bound method Solipsis3.custom_stoploss of <Solipsis_USDT.Solipsis_USDT object at 0x7f9f29769130>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper`

**Comment by werkkrew** [comment]
I think it might be an issue with the child strategy, while I try to sort it out you can work around it by using Solipsis_v3 directly and calling the strategy by name --strategy Solipsis3

**Comment by ladismrkolj** [comment]
Tried calling the parent strategy and same happens:
`Unexpected error 'Trade' object has no attribute 'open_date_utc' calling <bound method Solipsis3.custom_stoploss of <Solipsis3.Solipsis3 object at 0x7f8608ace1c0>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/user_data/strategies/Solipsis_v3.py", line 353, in custom_stoploss
    trade_dur = int((current_time.timestamp() - trade.open_date_utc.timestamp()) // 60)
AttributeError: 'Trade' object has no attribute 'open_date_utc'

2021-03-28 15:36:44,987 - freqtrade - ERROR - 'Trade' object has no attribute 'open_date_utc'
ERROR: 2`

**Comment by werkkrew** [comment]
Can you show me the exact command you are using?

I don't really know because I am running 3 copies of Solispsis live, 1 dry, and I am hyperopting 3 in addition to that I have not seen this error.

**Comment by ladismrkolj** [comment]
docker-compose run --rm  freqtrade hyperopt --hyperopt Solipsis3Hyp --strategy Solipsis_USDT --hyperopt-loss SharpeHyperOptLoss -i 5m -e 1000 -c user_data/config.json --timerange 20210201- --spaces buy

**Comment by werkkrew** [comment]
Right so you aren't using the parent strategy there.

Try this:

`docker-compose run --rm freqtrade hyperopt --hyperopt Solipsis3Hyp --strategy Solipsis3 --hyperopt-loss SharpeHyperOptLoss -i 5m -e 1000 -c user_data/config.json --timerange 20210201- --spaces buy`
