### ISSUE TITLE
dynamic ROI

### ISSUE THREAD

**Issue by tomismrkolj** [werkkrew/freqtrade-strategies#2]
Hi,
testing solipsis3 on Pi4. It works OK, no CPU clogging. Stoploss is rising as expected.
Regarding ROI: in strategy you have 
 # Recommended on 5m timeframe
    minimal_roi = {
        "0": 0.01,
        "360": 0.005,
        "720": 0
    }

Does this override dynamic ROI and should be hashed? I got one trade ROI at 1.2%. I guess it was from 0: 0.01 and not from dynamic ROI

**Comment by tomismrkolj** [comment]
In the mean time I watched ADA/USDT. Profit went up to 1.042%, then fell to 0.79% and was sold at this profit. So I guess this was dynamic ROI?

**Comment by tomismrkolj** [comment]
After few trades SKL/USDT was sold with loss as trailing stoploss. Stoploss jumped from -28% do about 2,7% when SKL was getting greener. And then it sudenly made stoploss with trailing. However trailing is false in my strategy file: 
# Positive Trailing
        'pos-trail': False,       # enable trailing once positive  
        'pos-threshold': 0.005,   # trail after how far positive
        'pos-trail-dist': 0.015   # how far behind to place the trail

![image](https://user-images.githubusercontent.com/15356681/112983167-a3bd2480-915d-11eb-862c-72bec6d54446.png)

**Comment by werkkrew** [comment]
> 
> 
> Hi,
> testing solipsis3 on Pi4. It works OK, no CPU clogging. Stoploss is rising as expected.
> Regarding ROI: in strategy you have
> # Recommended on 5m timeframe
> 
> ```
> minimal_roi = {
>     "0": 0.01,
>     "360": 0.005,
>     "720": 0
> }
> ```
> 
> Does this override dynamic ROI and should be hashed? I got one trade ROI at 1.2%. I guess it was from 0: 0.01 and not from dynamic ROI

The table is used depending on the "fallback" setting, which means if there is no trend then it will still obey the table.  Dynamic ROI at it's core is only meant to push profits past ROI when there are trends.



> 
> 
> After few trades SKL/USDT was sold with loss as trailing stoploss. Stoploss jumped from -28% to about -2,7% when SKL was getting greener. And then it sudenly made stoploss with trailing. However trailing is false in my strategy file:
> # Positive Trailing
> 
> ```
>     'pos-trail': False,       # enable trailing once positive  
>     'pos-threshold': 0.005,   # trail after how far positive
>     'pos-trail-dist': 0.015   # how far behind to place the trail
> ```
> 
> ![image](https://user-images.githubusercontent.com/15356681/112983167-a3bd2480-915d-11eb-862c-72bec6d54446.png)
> 
> ![image](https://user-images.githubusercontent.com/15356681/112986113-635fa580-9161-11eb-92dc-0e6b404008f6.png)


The positive trailing settings are just that, they allow/force the stoploss to trail the trade once it has reached at certain amount positive, that is not what happened here.

What you see here is the stoploss performing a bailout. What happened was, the stoploss was decaying as per the decay settings, it reached some low point and started to go back upward.  At that point the stoploss stopped using the decay value and instead started to trail the trade from the lowest observed point.  The idea here is to allow a trade to rebound without hitting the stoploss but to also catch it sooner if it starts to go back down again.

**I highly recommend you read the code and try to understand it before running this strategy live.**

**Comment by tomismrkolj** [comment]
I thought it was a bailout. I have different nick here, yesterday you gave me lesson (windsurfer) on Discord strategy channel. 
In continuation SLK/USDT fell even more rapidly, so bailout was successful.
![image](https://user-images.githubusercontent.com/15356681/113024156-b7c94c00-9186-11eb-8763-cd72063b6597.png)


What about ROI question? I had a lot to do with stoploss part yesterday as you remember. So we did not cover ROI yet...
Really I cannot see from last few hours of sideways market if ROI would go well over 1%. So for now: does dynamic ROI work already from the github posted strategy?

**Comment by tomismrkolj** [comment]
I also observed this:
![image](https://user-images.githubusercontent.com/15356681/113038274-a1c38780-9196-11eb-9b76-5aff3d0526ea.png)

I will contact you about ROI paramters later, but i must say that after testing solipsis today i got good feeling.

**Comment by tomismrkolj** [comment]
I went through dynamic ROI section and settings. Am i correct that higher profit factor means higher pullback buffer, which means with higher profit factor price fall from max observed profit before selling will be higher? This of course gives more chances of rebound so not selling to soon.
The settings that are not clear to me yet are  
'fallback': 'table',      # if no trend, do what? (table, roc, atr, roc-table, atr-table)
'min-roc-atr': 0.0075     # minimum roi value to return in roc or atr mode

You also mention that decay time of custom stoploss is good to equal ROI time. Which ROI time? Last ROI table entry or 'grow-time': 720,         # finish time of growth

**Comment by werkkrew** [comment]
> I went through dynamic ROI section and settings. Am i correct that higher profit factor means higher pullback buffer, which means with higher profit factor price fall from max observed profit before selling will be higher? This of course gives more chances of rebound so not selling to soon.

Yes that is correct.

Fallback is just what it sounds like.  If there is no trend, what do we use to determine ROI.  Options are: table, which uses the standard freqtrade defined table, ATR which uses some math around the ATR value, ROC, same as ATR with the ROC indicator, and atr/roc-table uses the larger of the indicator or the table (to prevent very small 0.001% sells) - min-roc-atr is an alternative way of dealing with this where when you are in roc/atr fallback mode the min-roc-atr value will be the smallest possible ROI returned if the indicator has a smaller value.



> You also mention that decay time of custom stoploss is good to equal ROI time. Which ROI time? Last ROI table entry or 'grow-time': 720, # finish time of growth

The ROI time where in the table  "XXXX": 0 - I am not sure my statement is correct but it felt like you want the ROI to be at the 0 point around the same time the stoploss is at its smallest value because that is the time you are ready to just be out of the trade.

The growth params in the dynamic-roi settings pertain to the RMI value which is required to be considered a trend, it grows over time.  The idea there being the longer a trade is open, the stronger of a trend we want to require to stay in the trade to so that we get out of very old trades more easily rather than stay in them forever.  You can easily override this by setting the same start/end RMI value or something similar.
