### ISSUE TITLE
custom_fiat clarification

### ISSUE THREAD

**Issue by jej** [werkkrew/freqtrade-strategies#4]
Hi Bryan,
I am not sure about this parameter. If my `stake_currency` is BUSD, should I use `custom_fiat="BUSD"`?
Thanks for your great work by the way.
Best regards.

**Comment by werkkrew** [comment]
It is only relevant if you have a stake currency of BTC or ETH, in which
case you'd set it to the stable coin or fiat you want to use as an
informative.

For example, if you have a BTC stake and the pair BTC/XLM in your white
list, custom_fiat will be used to determine which XLM informative to use,
if you want XLM/USDT you would use USDT.

Search the code for instances of self.custom_fiat and it should make sense.

**Comment by jej** [comment]
Thanks for your explanation. I can understand the python code itself but not the concept behind this parameter, sorry. To me freqtrade can only use one trade currency, but maybe I am wrong. Currently everything I trade is XXX/BUSD (including BTC/BUSD and ETH/BUSD). What do you suggest as `custom_fiat`? I promise I will go deeper into your code because it looks quite ingenious, but I am just uncertain about the importance of this parameter, and I don't want to ruin my backtests :)
Thanks for your support.

**Comment by werkkrew** [comment]
The setting does nothing unless you are using BTC or ETH as your stake,
which, you are not.  And so, that parameter is irrelevant for your use
case.

**Comment by jej** [comment]
Ok thanks. I can go forward now!
Best regards.
